Repository justdan96/tsMuxer, pull requests merged in 2019-11, with the labels that each got.

#25 update C++ standard from 11 to 14
  CMakeLists.txt
Labels: enhancement

#28 Correct EAC3 sampling rate and channel parsing
  tsMuxer/ac3Codec.cpp
Labels: bug

#29 Get rid of MAX_AV_PACKET_SIZE limitation
  tsMuxer/mpegStreamReader.cpp
Labels: bug

#30 Correct AAC frame size parsing
  tsMuxer/aac.cpp
Labels: bug

#32 Correct H265 Stream_Type
  tsMuxer/tsPacket.h
Labels: bug

#31 Parse channel number from 'esds' atom
  tsMuxer/movDemuxer.cpp
Labels: bug

#34 Actions will now fail if a executable isn't produced
  rebuild_linux_docker.sh
  rebuild_mxe_docker.sh
  rebuild_osxcross_docker.sh
Labels: bug

#35 Bug ac3 parsing
  tsMuxer/ac3Codec.cpp
Labels: bug

#36 check the correct directory for executables
  rebuild_linux_docker.sh
  rebuild_mxe_docker.sh
  rebuild_osxcross_docker.sh
Labels: bug

#38 use workaround for segfaults with statically-linked builds on Linux
  tsMuxer/CMakeLists.txt
Labels: bug

#48 Documentation Cleanup and Improvement
  COMPILING.md
  README.md
  tsMuxer/README.md
Labels: documentation
