Repository justdan96/tsMuxer, pull requests merged in 2019-12, with the labels that each got.

#50 Correct UHD video format in MPLS and CLPI
  tsMuxer/tsPacket.cpp
Labels: enhancement

#56 Corrected conflict beween min and std::min
  tsMuxer/dtsStreamReader.cpp
  tsMuxer/dtsStreamReader.h
  tsMuxer/mpegStreamReader.cpp
  tsMuxer/mpegStreamReader.h
Labels: bug

#68 enhance the OSX script for tsMuxerGUI to properly create the app bundle
  rebuild_osxcross_with_gui.sh
Labels: enhancement

#65 Make the GUI look for the main binary under "tsmuxer" and "tsMuxeR"
  tsMuxerGUI/tsmuxerwindow.cpp
  tsMuxerGUI/tsmuxerwindow.h
Labels: enhancement

#64 Replace the old QObject::connect syntax with the new one supported since Qt5
  tsMuxerGUI/muxForm.cpp
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: enhancement

#66 Fixes and cleanups
  CMakeLists.txt
  libmediation/fs/directory.cpp
  libmediation/fs/file.h
  libmediation/fs/osdep/file_unix.cpp
  libmediation/types/types.cpp
  libmediation/types/types.h
  tsMuxer/CMakeLists.txt
  tsMuxer/abstractCoreContext.h
  tsMuxer/abstractVideoDecoder.h
  tsMuxer/base64.cpp
  tsMuxer/base64.h
  tsMuxer/bitstream.h.ffmpeg
  tsMuxer/bswap.h
  tsMuxer/bufferedFileReader.cpp
  tsMuxer/bufferedRandomAccessReader.h
  tsMuxer/crc.cpp
  tsMuxer/crc.h
  tsMuxer/iso_writer.cpp
  tsMuxer/main.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxer/mpegStreamReader.cpp
  tsMuxer/mpegVideo.cpp
  tsMuxer/osdep/textSubtitlesRenderFT.cpp
  tsMuxer/psgStreamReader.h
  tsMuxer/scrambledInfo.h
  tsMuxer/singleFileMuxer.cpp
  tsMuxer/srtStreamReader.cpp
  tsMuxer/textSubtitles.cpp
  tsMuxer/textSubtitles.h
  tsMuxer/textSubtitlesRender.h
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsPacket.cpp
  tsMuxer/unused/vodCoreContext.cpp
  tsMuxer/unused/vodTransport.cpp
  tsMuxer/utf8Converter.cpp
  tsMuxer/vodTransport.h
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: enhancement

#72 add 32-bit Windows build script
  .github/workflows/windows_32.yml
  .github/workflows/windows_64.yml
Labels: enhancement

#80 change the bintray uploads to run on a nightly schedule
  .github/workflows/nightly.yml
Labels: enhancement

#79 Use QStandardPaths::findExecutable instead of QFile::exists for finding the main binary
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#73 Use standard-width types in convertUTF.h
  tsMuxer/convertUTF.h
Labels: bug

#81 add AppImage packaging for tsMuxerGUI on Linux
  rebuild_linux_with_gui_docker.sh
Labels: enhancement

#82 update README to explain nightly builds being uploaded to Bintray
  README.md
Labels: documentation

#86 fix typo causing nightly builds despite no changes
  bintray_nightly_upload.sh
Labels: bug

#88 Fix numbers appearing in places where the language code should
  tsMuxerGUI/lang_codes.h
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#70 Patch for UHD HDR10 and HDR10+
  tsMuxer/abstractStreamReader.h
  tsMuxer/blurayHelper.cpp
  tsMuxer/h264StreamReader.cpp
  tsMuxer/h264StreamReader.h
  tsMuxer/hevc.cpp
  tsMuxer/hevc.h
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/hevcStreamReader.h
  tsMuxer/main.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxer/mpeg2StreamReader.h
  tsMuxer/mpegStreamReader.cpp
  tsMuxer/nalUnits.cpp
  tsMuxer/nalUnits.h
  tsMuxer/psgStreamReader.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsMuxer.h
  tsMuxer/tsPacket.cpp
  tsMuxer/tsPacket.h
  tsMuxer/vc1StreamReader.h
Labels: enhancement, wip

#90 Automatic V3 for HEVC
  tsMuxer/main.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxer/metaDemuxer.h
  tsMuxer/muxerManager.cpp
  tsMuxer/muxerManager.h
Labels: enhancement, wip

#100 Set video stream number to 1
  tsMuxer/tsPacket.h
Labels: bug

#92 Correct TS Descriptors
  tsMuxer/ac3StreamReader.cpp
  tsMuxer/dtsStreamReader.cpp
  tsMuxer/h264StreamReader.cpp
  tsMuxer/hevcStreamReader.cpp
Labels: bug
