Repository justdan96/tsMuxer, pull requests merged in 2020-03, with the labels that each got.

#224 punctuation
  tsMuxerGUI/translations/about_ru.html
Labels: documentation

#229 fix the OBS nightly rebuild
  bintray_nightly_upload.sh
Labels: bug

#222 Fix broken ISO labels when using non-ASCII characters
  tsMuxer/convertUTF.cpp
  tsMuxer/convertUTF.h
  tsMuxer/iso_writer.cpp
  tsMuxer/osdep/textSubtitlesRenderFT.cpp
Labels: bug

#230 Fix Filename Truncation on Dot
  libmediation/types/types.cpp
Labels: bug

#232 update paths in MXE rebuild scripts
  rebuild_mxe32_with_gui_docker.sh
  rebuild_mxe_with_gui_docker.sh
Labels: bug

#231 Always keep M2TS descriptors in TS files
  tsMuxer/tsMuxer.cpp
Labels: error

#228 Сhanged address of test file
  README.md
Labels: documentation

#184 msys2
  COMPILING.md
  rebuild_msys2.sh
Labels: enhancement

#206 Keep track order on insertion
  tsMuxer/CMakeLists.txt
  tsMuxer/metaDemuxer.cpp
  tsMuxer/metaDemuxer.h
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: enhancement

#243 Non blu ray dolby vision
  tsMuxer/aacStreamReader.h
  tsMuxer/abstractStreamReader.h
  tsMuxer/ac3StreamReader.cpp
  tsMuxer/ac3StreamReader.h
  tsMuxer/avPacket.h
  tsMuxer/blurayHelper.cpp
  tsMuxer/dtsStreamReader.cpp
  tsMuxer/dtsStreamReader.h
  tsMuxer/dvbSubStreamReader.cpp
  tsMuxer/dvbSubStreamReader.h
  tsMuxer/h264StreamReader.cpp
  tsMuxer/h264StreamReader.h
  tsMuxer/hevc.cpp
  tsMuxer/hevc.h
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/hevcStreamReader.h
  tsMuxer/iso_writer.h
  tsMuxer/lpcmStreamReader.cpp
  tsMuxer/lpcmStreamReader.h
  tsMuxer/main.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxer/mpeg2StreamReader.cpp
  tsMuxer/mpeg2StreamReader.h
  tsMuxer/mpegAudioStreamReader.cpp
  tsMuxer/mpegAudioStreamReader.h
  tsMuxer/tsDemuxer.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsMuxer.h
  tsMuxer/tsPacket.cpp
  tsMuxer/tsPacket.h
  tsMuxer/vc1StreamReader.cpp
  tsMuxer/vc1StreamReader.h
Labels: enhancement

#242 Video streams must come first
  tsMuxer/metaDemuxer.cpp
Labels: bug

#246 Correct EAC3 descriptor
  tsMuxer/ac3Codec.cpp
  tsMuxer/ac3Codec.h
  tsMuxer/ac3StreamReader.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsPacket.cpp
  tsMuxer/tsPacket.h
Labels: enhancement

#245 Correct MPEG-2 streams Descriptors
  tsMuxer/mpeg2StreamReader.cpp
  tsMuxer/mpeg2StreamReader.h
  tsMuxer/mpegVideo.cpp
  tsMuxer/mpegVideo.h
Labels: enhancement

#248 Update hevcStreamReader.cpp
  tsMuxer/hevcStreamReader.cpp
Labels: bug

#250 Correct DV Profile 4
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsMuxer.h
Labels: enhancement

#249 [bug] MP4 If no moof, return at first mdat
  tsMuxer/movDemuxer.cpp
Labels: bug

#253 [Bug] prevent bitstream exception in hevc.cpp
  tsMuxer/hevc.cpp
Labels: bug

#251 Fix initializing lastDTS
  tsMuxer/metaDemuxer.h
Labels: bug

#254 For double video track, DV EL stream type = 0x06
  tsMuxer/tsMuxer.cpp
Labels: bug

#255 [bug] SEI nal does not always end by 0x80
  tsMuxer/hevc.cpp
Labels: bug

#260 [bug] Fix num_applicable_ops_minus1 size
  tsMuxer/nalUnits.cpp
Labels: bug

#263 [bug] Fix Subtitle Delay when concatenating M2ts
  tsMuxer/tsDemuxer.cpp
  tsMuxer/tsDemuxer.h
Labels: bug

#264 [bug] Fix DV profile for single track from Blu-ray
  tsMuxer/hevcStreamReader.cpp
Labels: bug

#238 cp tsMuxerGUI bin/
  rebuild_msys2.sh
Labels: enhancement

#266 Correct Eliding of track filenames
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#265 [bug] Add H265 to isVideoPID()
  tsMuxer/tsDemuxer.cpp
Labels: bug
