Repository justdan96/tsMuxer, pull requests merged in 2020-01, with the labels that each got.

#106 Correct UHD Bluray Folder Behavior
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#101 Correct Arrival Time Stamps
  tsMuxer/blurayHelper.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsMuxer.h
  tsMuxer/tsPacket.cpp
Labels: bug

#94 Solve HEVC Buffer Overflow Bug
  tsMuxer/hevc.h
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/hevcStreamReader.h
Labels: bug, wip

#113 FPS info read from VPS and SPS
  tsMuxer/hevc.cpp
  tsMuxer/hevc.h
  tsMuxer/hevcStreamReader.cpp
Labels: enhancement

#111 Dolby Vision Integration
  tsMuxer/blurayHelper.cpp
  tsMuxer/hevc.cpp
  tsMuxer/hevc.h
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/main.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsPacket.cpp
  tsMuxer/vod_common.h
Labels: enhancement

#112 Correct cpi table for uhd
  tsMuxer/tsPacket.cpp
Labels: bug

#120 Move BD V3 option to Blu-ray tab
  tsMuxer/main.cpp
  tsMuxerGUI/tsmuxerwindow.cpp
  tsMuxerGUI/tsmuxerwindow.ui
Labels: enhancement

#121 Standart to Standard
  tsMuxer/ac3Codec.cpp
  tsMuxer/lpcmStreamReader.cpp
  tsMuxer/mpegVideo.cpp
  tsMuxer/vc1Parser.cpp
Labels: enhancement

#124 Set TS video stream_id to 0xe0
  tsMuxer/tsMuxer.cpp
Labels: bug

#123 Warning on video format
  tsMuxer/tsPacket.cpp
Labels: enhancement

#125 Revert on change of ATS #101
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsMuxer.h
Labels: bug

#130 Fix fps info
  tsMuxer/hevc.cpp
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#134 Another portion of GUI cleanups
  rebuild_mxe32_with_gui_docker.sh
  rebuild_mxe_with_gui_docker.sh
  tsMuxerGUI/CMakeLists.txt
  tsMuxerGUI/checkboxedheaderview.cpp
  tsMuxerGUI/checkboxedheaderview.h
  tsMuxerGUI/codecinfo.h
  tsMuxerGUI/main.cpp
  tsMuxerGUI/muxForm.cpp
  tsMuxerGUI/muxForm.h
  tsMuxerGUI/tsMuxerGUI.pro
  tsMuxerGUI/tsmuxerwindow.cpp
  tsMuxerGUI/tsmuxerwindow.h
  tsMuxerGUI/tsmuxerwindow.ui
Labels: enhancement

#137 Fix wav64
  tsMuxer/lpcmStreamReader.cpp
  tsMuxer/wave.cpp
Labels: bug

#122 Change 'famaly' to 'family' in the tsMuxerGUI settings
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: enhancement, wip

#140 Fix 3d-plane / PID bug
  tsMuxer/main.cpp
Labels: bug

#146 Update of 4-bit frame_rate_code for PGS
  tsMuxer/psgStreamReader.cpp
Labels: bug

#147 Maximize maxCLL and maxFALL in index.bdmv
  tsMuxer/hevc.cpp
  tsMuxer/hevcStreamReader.cpp
Labels: bug

#153 Fix typos and grammar errors in readme and usage information
  README.md
  tsMuxer/main.cpp
Labels: enhancement

#160 Detect audio delay in MKV
  tsMuxer/matroskaDemuxer.cpp
  tsMuxer/matroskaDemuxer.h
Labels: enhancement

#163 Remove 3d-plane info for 2D BD-ROM
  tsMuxer/main.cpp
Labels: bug

#162 Fix bad looking fonts in Linux
  tsMuxer/osdep/textSubtitlesRenderFT.cpp
Labels: bug
