Repository justdan96/tsMuxer, pull requests merged in 2020-02, with the labels that each got.

#169 Bug: Shorten filename when adding more than two files
  tsMuxer/singleFileMuxer.cpp
Labels: bug

#171 Bug: Subtitle PIDs must start at 0x12A0 for HDR
  tsMuxer/psgStreamReader.cpp
  tsMuxer/tsMuxer.cpp
Labels: bug

#173 Bug: "Secondary" box greyed out for DTS Express 24bit
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: bug

#178 Improve documentation for building MSYS2 GUI
  COMPILING.md
Labels: documentation

#181 Try using the active code page if conversion from UTF-8 fails
  README.md
  libmediation/types/types.cpp
  tsMuxer/main.cpp
Labels: enhancement

#161 Implement support for default audio and subtitle tracks when muxing to Blu-ray
  README.md
  libmediation/fs/file.h
  tsMuxer/blurayHelper.cpp
  tsMuxer/blurayHelper.h
  tsMuxer/main.cpp
  tsMuxer/metaDemuxer.cpp
  tsMuxer/metaDemuxer.h
  tsMuxer/muxerManager.cpp
  tsMuxer/muxerManager.h
  tsMuxer/tsPacket.cpp
  tsMuxer/tsPacket.h
  tsMuxerGUI/tsmuxerwindow.cpp
  tsMuxerGUI/tsmuxerwindow.h
  tsMuxerGUI/tsmuxerwindow.ui
Labels: enhancement

#198 Update textSubtitlesRenderFT.cpp
  tsMuxer/osdep/textSubtitlesRenderFT.cpp
Labels: bug

#200 Add Dolby Vision fourCC codes
  tsMuxer/movDemuxer.cpp
Labels: enhancement

#203 Ts descriptors
  tsMuxer/aacStreamReader.h
  tsMuxer/abstractStreamReader.h
  tsMuxer/ac3StreamReader.cpp
  tsMuxer/ac3StreamReader.h
  tsMuxer/dtsStreamReader.cpp
  tsMuxer/dtsStreamReader.h
  tsMuxer/dvbSubStreamReader.cpp
  tsMuxer/dvbSubStreamReader.h
  tsMuxer/h264StreamReader.cpp
  tsMuxer/h264StreamReader.h
  tsMuxer/hevcStreamReader.cpp
  tsMuxer/hevcStreamReader.h
  tsMuxer/lpcmStreamReader.cpp
  tsMuxer/lpcmStreamReader.h
  tsMuxer/mpeg2StreamReader.cpp
  tsMuxer/mpeg2StreamReader.h
  tsMuxer/mpegAudioStreamReader.cpp
  tsMuxer/mpegAudioStreamReader.h
  tsMuxer/singleFileMuxer.cpp
  tsMuxer/tsMuxer.cpp
  tsMuxer/tsPacket.cpp
  tsMuxer/tsPacket.h
  tsMuxer/vc1StreamReader.cpp
  tsMuxer/vc1StreamReader.h
Labels: enhancement

#205 Reading fragmented MP4
  tsMuxer/movDemuxer.cpp
  tsMuxer/movDemuxer.h
Labels: enhancement

#199 Update Changelog, Update Readme and Add Contributors
  CHANGELOG.md
  README.md
  bintray_nightly_upload.sh
Labels: documentation

#213 [bug]Fix subtitle timestamp
  tsMuxer/tsDemuxer.cpp
Labels: bug

#215 Support of m4v files
  tsMuxer/metaDemuxer.cpp
  tsMuxerGUI/tsmuxerwindow.cpp
Labels: enhancement

#196 Add a translation file for the GUI, mark (un)translatable content properly
  tsMuxerGUI/CMakeLists.txt
  tsMuxerGUI/muxForm.cpp
  tsMuxerGUI/translations/tsmuxergui_en.ts
  tsMuxerGUI/tsMuxerGUI.pro
  tsMuxerGUI/tsmuxerwindow.cpp
  tsMuxerGUI/tsmuxerwindow.ui
Labels: enhancement
